import Head from "next/head";
import Login from "./login";
import supabase from "./api/supabase";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import Loading from "./components/loading";
import style from "../styles/Home.module.css";

export default function Home() {
  const router = useRouter();
  const [userfound, setUserfound] = useState(false);
  const [isloading, setIsloading] = useState(true);

  let matchtry = async () => {
    const { data, error } = await supabase.auth.getSession();
    if (data) {
      setIsloading(true);
      usermatch(data.session);
    }
  };

  useEffect(() => {
    setIsloading(true);
    matchtry();
  }, []);

  let usermatch = async (sessionuser) => {
    setIsloading(true);
    if (sessionuser) {
      setIsloading(true);
      let { data: users, error } = await supabase
        .from("users")
        .select("*")
        .eq("id", sessionuser.user.id);
      if (users) {
        setUserfound(true);
        setIsloading(false);
      } else if (error) {
        setIsloading(false);
        router.push("/login");
      }
    } else {
      setIsloading(false);
      router.push("/login");
    }
  };

  useEffect(() => {
    if (userfound == true) {
      router.push("/home");
    }
  }, [userfound]);

  return (
    <div className={style.firstdiv}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isloading && <Loading />}
    </div>
  );
}
